/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "on-tertiary-fixed-variant": "#4e6a60",
            "inverse-on-surface": "#535557",
            "on-error-container": "#ff9993",
            "tertiary-fixed": "#d8f8eb",
            "surface": "#0c0e10",
            "inverse-primary": "#00687d",
            "surface-bright": "#252d33",
            "surface-container": "#161a1e",
            "surface-container-high": "#1b2025",
            "surface-dim": "#0c0e10",
            "inverse-surface": "#f9f9fc",
            "outline-variant": "#42494e",
            "surface-container-low": "#111416",
            "primary-fixed-dim": "#89e1fc",
            "on-secondary": "#142227",
            "on-error": "#490106",
            "on-background": "#e0e6ed",
            "error-container": "#7f2927",
            "on-tertiary-fixed": "#314d44",
            "on-primary-fixed-variant": "#006478",
            "on-primary-fixed": "#004655",
            "on-surface-variant": "#a6acb2",
            "surface-variant": "#20262c",
            "background": "#0c0e10",
            "tertiary-container": "#d2f2e5",
            "primary-container": "#004e5e",
            "on-primary": "#004756",
            "primary": "#7bd3ed",
            "primary-dim": "#6cc5df",
            "on-secondary-container": "#b3c2c8",
            "secondary-fixed": "#d6e5ec",
            "on-surface": "#e0e6ed",
            "tertiary-fixed-dim": "#caeadd",
            "surface-container-highest": "#20262c",
            "tertiary": "#e6fff4",
            "tertiary-dim": "#caeadd",
            "on-secondary-fixed": "#344147",
            "on-primary-container": "#85ddf7",
            "secondary-fixed-dim": "#c8d7de",
            "on-tertiary": "#48655b",
            "outline": "#70767c",
            "on-tertiary-container": "#405c53",
            "on-secondary-fixed-variant": "#505e64",
            "surface-tint": "#7bd3ed",
            "primary-fixed": "#b1ecff",
            "surface-container-lowest": "#000000",
            "secondary-container": "#303d43",
            "error-dim": "#bb5551",
            "secondary": "#92a0a7",
            "secondary-dim": "#92a0a7",
            "error": "#ee7d77"
        },
        "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
        },
        "fontFamily": {
            "headline": ["Inter"],
            "body": ["Inter"],
            "label": ["Inter"]
        }
    },
  },
  plugins: [],
}
